### ISSUE TITLE
A Website for the Rocker Project?

### ISSUE THREAD

**Issue by cboettig** [rocker-org/website#1]
Hey @eddelbuettel ,

I put together a sketch for a [Rocker website](https://rocker-org.github.io/website), curious what you think.  The wiki is good, but doesn't seem super discoverable for new users, so I often end up pointing to other sites for someone trying to get started and was thinking we may as well have our own.  

If we go with a website, I was thinking about registering a domain-name for the purpose. What do you think of `https://rocker-project.org`?

Cheers,

**Comment by eddelbuettel** [comment]
I like it and already made a commit :)

**Comment by cboettig** [comment]
Nice, thanks!  If no objections, I'll go and register `rocker-project.org` then?  `rocker.org` seemed too vague and is probably taken.

**Comment by eddelbuettel** [comment]
Yes, and I was contemplating asking for a subdomain within r-project.org but that us too presumptious.

**Comment by eddelbuettel** [comment]
All good, and ready to be closed.
