### ISSUE TITLE
Recent commits not showing

### ISSUE THREAD

**Issue by louisaslett** [rocker-org/website#21]
I might be missing something, but recent commits don't seem to be showing on the deployed site.  For example, this page:

<https://github.com/rocker-org/website/blob/master/content/use/singularity.md>

is not reflected here, with the section "Additional Options for RStudio >= 1.3.x" not appearing at all:

<https://www.rocker-project.org/use/singularity/>

**Comment by cboettig** [comment]
yup, thanks for the ping, site generation isn't automated on PRs so I think we just need to manually rebuild the sources...

**Comment by eitsupi** [comment]
The deployment method has changed, so now we don't have to build on local.
