### ISSUE TITLE
GitHub and Docker Hub links in footer prefixed with https://www.rocker-project.org

### ISSUE THREAD

**Issue by dskard** [rocker-org/website#23]
on https://www.rocker-project.org/, the GitHub and Docker Hub link urls (in the website footer) are prefixed with `https://www.rocker-project.org/`:
1. GitHub link leads to https://www.rocker-project.org/https:/github.com/rocker-org
2. Docker Hub link leads to https://www.rocker-project.org/https:/hub.docker.com/u/rocker

**Comment by eitsupi** [comment]
Closed by #44
