### ISSUE TITLE
Broken link on Extending Images

### ISSUE THREAD

**Issue by ProbablePattern** [rocker-org/website#24]
The link on the word "here" in the following sentence is broken.
"See here for the source code that defines the rocker/r-ver image that many Rocker images are based on."

This is located on the Extending Images page.

**Comment by eddelbuettel** [comment]
Relevant file https://raw.githubusercontent.com/rocker-org/website/master/content/use/extending.md
Quoting "See [here](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/latest.Dockerfile)"
We probably want to point to https://github.com/rocker-org/rocker-versioned2/ but then everything is different with the stacks etc.  We could point to r-base :)  That hasn't changed.
