### ISSUE TITLE
Repetition of paragraph

### ISSUE THREAD

**Issue by ratnanil** [rocker-org/website#28]
Most of the content in this paragraph is repeated in the next one (see permalinks below). Remove one?

https://github.com/rocker-org/website/blob/ab636ccbfe54617f12bbe271cd59e5809c193d5d/content/use/managing_users.md?plain=1#L32-L40

https://github.com/rocker-org/website/blob/ab636ccbfe54617f12bbe271cd59e5809c193d5d/content/use/managing_users.md?plain=1#L43

**Comment by eitsupi** [comment]
Hi, thank you for catching this!
Definitely needs to be fixed...
