### ISSUE TITLE
CDN (Cloudfront) change the appearance and rewrite the links?

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/website#49]
@cboettig Could you please check to see if the content rewriting by CDN setting is enabled on Netlify?
I found the following thread.

https://answers.netlify.com/t/cdn-change-netlify-cdn-or-cloudfront/3582

> Thanks for reaching out! At the moment when you enable asset optimization of any kind, we’ll serve assets from Cloudfront. This includes enabling pretty URL’s. This only happens for assets that are referenced in your html using relative paths. If you use full paths then it will still load them locally. While this is a behavior that we may change in the future, there are no immediate plans to do so.

Looking at the HTML source, font settings, etc. have been removed, and there seems to be a clear difference in appearance when displayed in the browser.

Local

![image](https://user-images.githubusercontent.com/50911393/173212808-8af2ab82-1e80-4411-998f-8ffa87b49495.png)

Netlify (#48)

![image](https://user-images.githubusercontent.com/50911393/173212828-3664559b-8018-4962-9615-da9bba21e040.png)

And, we can also see that the url has been rewritten.
For example, `CODE_OF_CONDUCT.html` to `code_of_conduct`.

It is possible that this was also the cause of #23.

**Comment by cboettig** [comment]
Not sure I follow entirely here what is going on, but I do think CDN is enabled by default and it looks like Netlify is already re-writing the assets to the CDN. e.g. if you go View Source on the deployed site, it shows assets like stylesheet being rewritten as: 


```
<link href='https://d33wubrfki0l68.cloudfront.net/css/bef421e66c07d4edad7fbfe0768235fd0d8885e9/styles.css' rel='stylesheet'/>
```

note the Cloudfront address.  Is this causing issues?  I think we can configure this behavior if necessary?  not clear to me the connection between the style rendering and the cdn here.  


 

<br class="Apple-interchange-newline">
</body>
</html><html>
<body>




<link href='https://d33wubrfki0l68.cloudfront.net/css/bef421e66c07d4edad7fbfe0768235fd0d8885e9/styles.css' rel='stylesheet'/>
 

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by eitsupi** [comment]
@cboettig I don't have a Netlify account so I don't know what the settings screen looks like, but the comments below suggest that this setting is optional and can be turned off.

> The domain in the screenshot is the domain where any assets which were modified by the asset optimizations in the build settings will be served. If you disable asset optimization in the site build settings, assets will no longer be served from this domain.

https://answers.netlify.com/t/cdn-change-netlify-cdn-or-cloudfront/3582/2

**Comment by cboettig** [comment]
Thanks. Just trying to wrap my head around the issue -- why do we want to disable the CDN?  Is the CDN not correctly rendering the assets?  From the thread, it looks like using full urls instead of relative urls will also bypass the CDN, but maybe that's not easy to do in quarto?  

I'll poke around for the option to turn of the CDN.

**Comment by eitsupi** [comment]
> why do we want to disable the CDN? Is the CDN not correctly rendering the assets?

I think the web page is rewritten by Netlify.
Due to this, the fonts are displayed differently than expected, and rounded corners seem to be squared off.

The official Quarto site also appears to be deployed on Netlify, but does not appear to be affected as such.
https://quarto.org/

**Comment by eddelbuettel** [comment]
I never ever understood the obsession with Netlify. I sometimes asked and I think I got a partial answer once or twice (and have promptly forgotten what it was about -- maybe something about private vs public repos?).  I am rather content with simply hosting everything I don't just host here (at home) over at GitHub via Pages, and added more content over the years.  It just works with a simple commit -- good enough for me.  My $0.02, but I am not the one putting in the work so deferring to @eitsupi.

**Comment by eitsupi** [comment]
> Do we want to publish to a different branch or a a `docs/` dir on the main branch if we go pure-GitHub pages?

For searchability, it is better to use the `gh-pages` branch, I think. (I think it confuses people when they search for a document and both the `md` and `html` files come up in the search results on GitHub.)
This can be accomplished with a small modification to GitHub Actions and we will create a PR later.

**Comment by eitsupi** [comment]
Leave it open until the time when https://www.rocker-project.org/ is finally redirected to GitHub Pages.
