### ISSUE TITLE
Additional 'use' pages

### ISSUE THREAD

**Issue by cboettig** [rocker-org/website#6]
- Using Shiny
- add Use menu link for singularity / hpc
- developer info: S6 init, etc
- X11

**Comment by cboettig** [comment]
mostly done

**Comment by eddelbuettel** [comment]
Nice. I just spotted the 'what BLAS do we use' -- there is also `sessionInfo()` in R which has it:

```r
R> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.1 LTS

Matrix products: default
BLAS: /usr/lib/x86_64-linux-gnu/openblas/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/libopenblasp-r0.2.20.so
[...]
```

(cheating, from my desktop ...)

**Comment by cboettig** [comment]
Good call, that's much nicer! just pushed
