### ISSUE TITLE
Add page for community-derived images

### ISSUE THREAD

**Issue by cboettig** [rocker-org/website#7]
- i.e. [rocker-bayesian](https://github.com/mavelli/rocker-bayesian) from https://github.com/rocker-org/rocker/issues/293

Should probably also add a Guide to setting up such images; e.g.  

- setting up automated builds
- setting builds to auto-trigger whenever the parent rocker image is rebuilt
- how to support version tags. 
- link [Dockerfile best-practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) 
- maybe highlight common issues like `install2.r` syntax for additional repos and dependencies etc

**Comment by eitsupi** [comment]
I close this as I believe it has been resolved in the updated current document.
