### ISSUE TITLE
Clarify which container uses clang?

### ISSUE THREAD

**Issue by mikemahoney218** [rocker-org/website#74]
Hey folks! Thanks for the awesome service y'all provide.

I am _pretty sure_ this is a typo, and these descriptions should be flipped:
https://github.com/rocker-org/website/blob/24ec305f8b87cbbf5f08ec6ab55a4bbc9a2e04a8/images/base/r-devel.md?plain=1#L45

Is my guess right?

**Comment by eddelbuettel** [comment]
Nice archeological dig, those are ancient containers of mine.  I think what you suggest is correct.

**Comment by mikemahoney218** [comment]
:laughing: I came across it while doing some digging trying to find an easy container for testing LLVM issues, following today's CRAN drama. There's extremely little online even talking about R-and-clang it turns out!

**Comment by eddelbuettel** [comment]
I had some email with CRAN about some packages of mine (very cordial, as usual, and they helped greatly) and warnings from `clang-15` where mentioned in passing.  I have not heard personally but a friend pointed me to the CRAN reports page for `data.table`.

It's always a pain but net-net compiler warnings tend to be good and helpful...

**Comment by eddelbuettel** [comment]
I often just start from the `r-base` (aka `rocker/r-base`) container and add a new compiler. It is usually there in Debian testing + unstable.

**Comment by eddelbuettel** [comment]
I said "start" :)  I didn't say it always is cookies cutter :)   For brand new compilers (for example the UK site of CRAN sometimes has very early versions) you can get builds (for .deb which I care about) from PPAs at launchpad, I forget now which but Google knows. The Austian end of CRAN is much closer to plain (yet current/fresh aka 'unstable/testing'.  And yes having their set in containers would be nice but life is short and nobody has done.  Their setup scripts are in a public SVN ...

**Comment by eddelbuettel** [comment]
@mikemahoney218 Just in case you hadn't seen:  https://twitter.com/GaborCsardi/status/1578104458613231624

**Comment by mikemahoney218** [comment]
Thank you so much!

**Comment by eddelbuettel** [comment]
_De nada_ especially as the ubsan-clang one does not claim to be an always-current clang setup.  Thanks to @gaborcsardi for providing those.

I think we can close this now.
